#pragma once

#define MAX_TRANSFER_BUFFER_SIZE 50000

class MyTransfer
{

public:
	DWORD mOriginalSize;
	BYTE mOriginal[MAX_TRANSFER_BUFFER_SIZE];
	DWORD mOriginalSize2;
	BYTE mOriginal2[MAX_TRANSFER_BUFFER_SIZE];
	DWORD mOriginalSize_C;
	BYTE mOriginal_C[MAX_TRANSFER_BUFFER_SIZE];
	DWORD mOriginalSize_R;
	BYTE mOriginal_R[MAX_TRANSFER_BUFFER_SIZE];

	MyTransfer(void);

	BOOL Init(void);
	void Free(void);

	void B_CONNECT_OK(int tRandomNumber);
	void B_TEMP_REGISTER_RECV(int tResult);
	void B_REGISTER_AVATAR_RECV(AVATAR_INFO* tAvatarInfo, int tEffectValue[MAX_AVATAR_EFFECT_SORT_NUM][2]);
	void B_BROADCAST_WORLD_INFO(WORLD_INFO* tWorldInfo, TRIBE_INFO* tTribeInfo);
	void B_BROADCAST_WORLD_INFO2(WORLD_INFO* tWorldInfo, TRIBE_INFO* tTribeInfo);
	void B_AUTO_CHECK_ASK_SEND(int tAnswer);
	void B_AVATAR_ACTION_RECV(int tServerIndex, DWORD tUniqueNumber, OBJECT_FOR_AVATAR* tAvatar, int tCheckChangeActionState);
	void B_AVATAR_ACTION_RECV2(int tServerIndex, DWORD tUniqueNumber, OBJECT_FOR_AVATAR* tAvatar, int tCheckChangeActionState);
	void B_AVATAR_EFFECT_VALUE_INFO(int tServerIndex, DWORD tUniqueNumber, int tEffectValue[MAX_AVATAR_EFFECT_SORT_NUM][2], int tEffectValueState[MAX_AVATAR_EFFECT_SORT_NUM]);
	void B_AVATAR_CHANGE_INFO_1(int tServerIndex, DWORD tUniqueNumber, int tSort, int tValue01, int tValue02, int tValue03);
	void B_MONSTER_ACTION_RECV(int tServerIndex, DWORD tUniqueNumber, OBJECT_FOR_MONSTER* tMonster, int tCheckChangeActionState);
	void B_ITEM_ACTION_RECV(int tServerIndex, DWORD tUniqueNumber, OBJECT_FOR_ITEM* tItem, int tCheckChangeActionState);
	void B_ITEM_ACTION_RECV2(int tServerIndex, DWORD tUniqueNumber, OBJECT_FOR_ITEM* tItem, int tCheckChangeActionState);
	void B_GENERAL_NOTICE_RECV(char tContent[MAX_CHAT_CONTENT_LENGTH], int type = 0);
	void B_PROCESS_ATTACK_RECV(ATTACK_FOR_PROTOCOL* tAttackInfo);
	void B_AVATAR_CHANGE_INFO_2(int tSort, int tValue);
	void B_PROCESS_DATA_RECV(int tResult, int tSort, BYTE tData[MAX_BROADCAST_DATA_SIZE]);
	void B_DEMAND_ZONE_SERVER_INFO_2_RESULT(int tResult, char tIp[16], int tPort);
	void B_USE_HOTKEY_ITEM_RECV(int tResult, int tPage, int tIndex);
	void B_USE_INVENTORY_ITEM_RECV(int tResult, int tPage, int tIndex, int tValue, int tValue2);
	void B_IMPROVE_ITEM_RECV(int tResult, int tCost, int iValue);
	void B_REFINE_ITEM_RECV(int tResult, int tCPCost, int iValue);
	void B_ADD_ITEM_RECV(int tResult, int tCost);
	void B_EXCHANGE_ITEM_RECV(int tResult, int tCost, int tValue[6]);
	void B_SEND_ITEM_NEW(int tResult, int tPage, int tIndex, int tValue1, int tValue2, int tValue3, int tValue4, int tValue5, int tValue6);
	void B_HIGH_ITEM_RECV(int tResult, int tCost, int tValue[6]);
	void B_LOW_ITEM_RECV(int tResult, int tCost, int tValue[6]);
	void B_MAKE_ITEM_RECV(int tResult, int tValue[6]);
	void B_GEAR_BREAK_RECV(int tResult, int tMoney, int tValue[6]);
	void B_MAKE_SKILL_RECV(int tResult, int tValue[6]);
	void B_START_PSHOP_RECV(int tResult, PSHOP_INFO* tPShopInfo);
	void B_END_PSHOP_RECV(int tResult);
	void B_DEMAND_PSHOP_RECV(int tResult, PSHOP_INFO* tPShopInfo);
	void B_PSHOP_ITEM_INFO_RECV(DWORD tUniqueNumber, char tAvatarName[MAX_AVATAR_NAME_LENGTH], int tPage, int tIndex, int tPShopItemInfo[9], int tSocket[MAX_SOCKETSYSTEM_ARRAY]);
	void B_BUY_PSHOP_RECV(int tResult, int tCost, int tPage, int tIndex, int tValue[6], int tSocket[MAX_SOCKETSYSTEM_ARRAY]);
	void B_PROCESS_QUEST_RECV(int tResult, int tSort, int tPage, int tIndex, int tXPost, int tYPost);
	void B_CHANGE_TO_TRIBE4_RECV(int tResult);
	void B_GENERAL_CHAT_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH]);
	void B_SECRET_CHAT_RECV(int tResult, int tZoneNumber, char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH], int type = 0);
	void B_GENERAL_SHOUT_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH]);
	void B_GET_CASH_SIZE_RECV(int tCashSize, int tSort);
	void B_BUY_CASH_ITEM_RECV(int tResult, int tCashSize, int tPage, int tIndex, int tValue[6]);
	void B_DUEL_ASK_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], int tSort);
	void B_DUEL_CANCEL_RECV(void);
	void B_DUEL_ANSWER_RECV(int tAnswer);
	void B_DUEL_START_RECV(int tDuelState[3], int tRemainTime, int tIsPotionUsable);
	void B_DUEL_TIME_INFO(int tRemainTime);
	void B_DUEL_END_RECV(int tResult);
	void B_TRADE_ASK_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], int tLevel);
	void B_TRADE_CANCEL_RECV(void);
	void B_TRADE_ANSWER_RECV(int tAnswer);
	void B_TRADE_START_RECV(int tTradeMoney, int tTrade[MAX_TRADE_SLOT_NUM][4], int tTradeMoney2, int tTradeSocket[8][MAX_SOCKETSYSTEM_ARRAY]);
	void B_TRADE_STATE_RECV(int tTradeMoney, int tTrade[MAX_TRADE_SLOT_NUM][4], int tTradeMoney2, int tTradeSocket[8][MAX_SOCKETSYSTEM_ARRAY]);
	void B_TRADE_MENU_RECV(int tCheckMe);
	void B_TRADE_END_RECV(int tResult);
	void B_FRIEND_ASK_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH]);
	void B_FRIEND_CANCEL_RECV(void);
	void B_FRIEND_ANSWER_RECV(int tAnswer);
	void B_FRIEND_MAKE_RECV(int tIndex, char tAvatarName[MAX_AVATAR_NAME_LENGTH]);
	void B_FRIEND_FIND_RECV(int tIndex, int tZoneNumber);
	void B_FRIEND_DELETE_RECV(int tIndex);
	void B_TEACHER_ASK_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH]);
	void B_TEACHER_CANCEL_RECV(void);
	void B_TEACHER_ANSWER_RECV(int tAnswer);
	void B_TEACHER_START_RECV(int tSort, char tAvatarName[MAX_AVATAR_NAME_LENGTH]);
	void B_TEACHER_END_RECV(void);
	void B_TEACHER_STATE_RECV(int tResult);
	void B_PARTY_ASK_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH]);
	void B_PARTY_CANCEL_RECV(void);
	void B_PARTY_ANSWER_RECV(int tAnswer);
	void B_PARTY_MAKE_RECV();
	void B_PARTY_JOIN_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], int type);
	void B_PARTY_INFO_RECV(char tAvatarName1[MAX_AVATAR_NAME_LENGTH], char tAvatarName2[MAX_AVATAR_NAME_LENGTH], char tAvatarName3[MAX_AVATAR_NAME_LENGTH], char tAvatarName4[MAX_AVATAR_NAME_LENGTH], char tAvatarName5[MAX_AVATAR_NAME_LENGTH], int type);
	void B_PARTY_CHAT_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH], int type = 0);
	void B_PARTY_LEAVE_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], int type);
	void B_PARTY_EXILE_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], int type);
	void B_PARTY_BREAK_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], int type);
	void B_GUILD_ASK_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH]);
	void B_GUILD_CANCEL_RECV(void);
	void B_GUILD_ANSWER_RECV(int tAnswer);
	void B_GUILD_WORK_RECV(int tResult, int tSort, GUILD_INFO* tGuildInfo);
	void B_GUILD_NOTICE_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH], int type = 0);
	void B_GUILD_CHAT_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH], int type = 0);
	void B_GUILD_FIND_RECV(int tResult);
	void B_GUILD_LOGIN_INFO(char tAvatarName[MAX_AVATAR_NAME_LENGTH], int type = 0);
	void B_TRIBE_WORK_RECV(int tResult, int tSort, BYTE tData[MAX_TRIBE_WORK_SIZE]);
	void B_TRIBE_NOTICE_RECV(int tType, char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH], int type = 0);
	void B_TRIBE_CHAT_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH]);
	void B_TRIBE_CHAT_RECV2(char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH]);
	void B_FACTION_NOTICE_RECV(char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tContent[MAX_CHAT_CONTENT_LENGTH], int type = 0);
	void B_TRIBE_BANK_RECV(int tResult, int tSort, int tTribeBankInfo[MAX_TRIBE_BANK_SLOT_NUM], int tMoney);
	void B_TRIBE_VOTE_RECV(int tResult, int tSort, int tValue);
	void B_TRIBE_ALLIANCE_INFO(int tSort, int tValue);
	void B_BROADCAST_INFO_RECV(int tInfoSort, BYTE tInfoData[MAX_BROADCAST_INFO_SIZE]);
	void B_BROADCAST_INFO_RECV2(int tInfoSort, BYTE tInfoData[MAX_BROADCAST_INFO_SIZE]);
	void B_049_TYPE_BATTLE_INFO(int tTribeUserNum[4], int tRemainTime);
	void B_051_TYPE_BATTLE_INFO(int tExistStone[4]);
	void B_053_TYPE_BATTLE_INFO(int tRemainTime);
	void B_VOD_BATTLE_INFO(int tTribeUserKillNum[4]);
	void B_194_BATTLE_INFO(int tTribeUserNum[4]);
	void B_194_BATTLE_COUNTDOWN(int tTime);
	void B_267_TYPE_BATTLE_INFO(int tTribeUserNum[4], int tRemainTime);
	void B_GM_COMMAND_INFO(int tSort, BYTE tData[MAX_TRIBE_WORK_SIZE]);
	void B_GM_COMMAND_INFO2(int tSort, BYTE tData[MAX_TRIBE_WORK_SIZE]);
	void B_ANIMAL_STATE_RECV(int tValue01, int tValue02);
	void B_SOCKET_ITEM_RECV(int tResult, int tSort, int tSocket[MAX_SOCKETSYSTEM_ARRAY]);
	void B_COSTUME_STATE_RECV(int tResult, int tValue01, int tValue02, int iPage, int iInvenSlot, int iInvenIndex, int pItemIndex);
	void B_AUTOHUNT_RECV(int tServerIndex, DWORD tUniqueNumber, int tAutoState);
	void W_DAILY_MISSION_RECV(int tResult, int tSort, int tWars, int tPVPKills, int tPVMKills, int tOnlineTime, int tItem, int tPage, int tIndex, int tXPost, int tYPost);
	void B_BEGINNER_REWARD_RECV(int tResult, int iPage, int iInvenSlot, int iInvenSlot2, int iInvenIndex, int iInvenIndex2, int tValue[8], int tImproveValue);
	void B_WARLORD_V2_RECV(int tResult, int tCost, int tValue[6]);
	void B_REMAIN_TIME_RECV(int tRemainTime);
	void B_BOOZE_DRINK_RECV(int tResult, int tDrinkIndex);
	void PC_CAFE_PETTOBAG_RECV(int tResult, int tItemIndex, int iPage, int iInvenSlot, int iInvenIndex, int tItemModifier);
	void REFRESH_BAG_ITEM(int tResult, int tItemIndex, int iPage, int iIndex, int iInvenSlot);
	void B_COSTUME_HIDE_RECV(int tResult);
	void B_ENGRAVE_WEAPON_RECV(int tResult, int tMoney, int tCP, int tProtectionCharm, int tImproveState);
	void B_UPGRADE_TO_LEGENDARY_RECV(int tResult, int tMode, int tCost, int tCPCost, int tValue[6]);
	void B_TOWER_INFO_RECV(TOWER_INFO* tTowerInfo);
	void B_TOWER_UPGRADE_RECV(int tResult, int tPage, int tIndex);
	void B_ADD_AMULET_ABILITY(int tResult, int tMemory, int tValue1, int tValue2, int tValue3);
	void B_DEMAND_BLOODSTAINED_SHOP_INFO_RECV(int tPages, BLOODSTAINEDSHOP_INFO* tInfo);
	void B_BUY_BLOODSTAINED_SHOP_RECV(int tResult, int tRemainPoints, int tPage, int tIndex, int tValue[6]);
	void B_BUY_CAPSULE_SHOP_RECV(int tResultQuantity, int tPage, int tIndex1, int tIndex2, int tInvenSlot1, int tInvenSlot2, int tCapsuleType, int tCost, int tValue[8]);
	void B_ULTIMATE_ENCHANT_RECV(int tResult, int tCost, int tImproveValue, int tValue);
	void B_GET_CURRENT_HERO_RANKING_RECV(int tResult, HERO_RANKING_INFO* hRank);
	void B_CLAIM_HERO_RANK_REWARD_RECV(int tResult, int tRewardValue);
	void B_GET_OLD_HERO_RANKING_RECV(int tResult, HERO_RANKING_INFO* hRank);
	void B_GET_CASH_ITEM_INFO_RECV(int tResult, int tVersion, int tCashItemInfo[4][14][10][4]);
	void B_PROXY_SHOP(int tUserIndex, DWORD tUniqueNumber, float tUserLocation[3], char tAvatarName[MAX_AVATAR_NAME_LENGTH], char tShopName[27], int tMode);
	void B_DEMAND_PROXY_INFO(int a, int b, PROXYSHOP_INFO* mProxy);
	void B_BUY_PROXY_SHOP_ITEM(int tResult, PROXYSHOP_INFO* tProxyInfo, int tPage, int tIndex, int tValue[12]);
	void B_CLAIM_MONEY_PROXY_SHOP(int tResult, int aMoney, int aMoney2);
	void B_FISHING_STATE_RECV(int tUserIndex, DWORD tUniqueNumber, int tFishingMode, int tFishingState, int tFishingStep);
	void B_FISHING_RESULT_RECV(int tUserIndex, DWORD tUniqueNumber, int tFishingMode, int tFishingState, int tFishingStep);
	void B_FISHING_SUCCESS_RECV(int tResult, int tItemIndex, int tPage, int tIndex, int tInvenSlot);
	void B_FACTION_TRAP_RECV(FACTION_TRAP* tFactionTrap);
	void B_ZONE_88_INFO_RECV(int tSort, int tState);
	void B_ZONE_88_INFO2_RECV(int tSort, char tAvatarName[MAX_AVATAR_NAME_LENGTH], int tTribe);
	void B_CLAIM_LOGIN_REWARD_RECV(int tSort, int tItemIndex, int tPage, int tIndex, int tInvenIndex, int tLoginClaimState, int tLoginEventMallPoint);
	void B_RETURN_TO_TOWN_RECV();
	void B_CLOAK_UPGRADE_RECV(int tResult, int tValue[6]);
	void B_UNSEAL_LEGENDARY_RECV(int tResult, int tCost, int tValue[6]);
};
extern MyTransfer mTRANSFER;