#include "MainApp.h"

MyWork mWORK;
MyWork::MyWork(void)
{
}

BOOL MyWork::Init(void)
{
	int index01;

	for (index01 = 0; index01 < 256; index01++)
	{
		W_FUNCTION[index01].PROC = NULL;
	}
	// W_TEMP_REGISTER_SEND
	mWorkerPacketSize[P_TEMP_REGISTER_SEND] = S_TEMP_REGISTER_SEND;
	W_FUNCTION[P_TEMP_REGISTER_SEND].PROC = W_TEMP_REGISTER_SEND;
	// W_REGISTER_AVATAR_SEND
	mWorkerPacketSize[P_REGISTER_AVATAR_SEND] = S_REGISTER_AVATAR_SEND;
	W_FUNCTION[P_REGISTER_AVATAR_SEND].PROC = W_REGISTER_AVATAR_SEND;
	// W_CLIENT_OK_FOR_ZONE_SEND
	mWorkerPacketSize[P_CLIENT_OK_FOR_ZONE_SEND] = S_CLIENT_OK_FOR_ZONE_SEND;
	W_FUNCTION[P_CLIENT_OK_FOR_ZONE_SEND].PROC = W_CLIENT_OK_FOR_ZONE_SEND;
	// W_AVATAR_ACTION_SEND
	mWorkerPacketSize[P_AVATAR_ACTION_SEND] = S_AVATAR_ACTION_SEND;
	W_FUNCTION[P_AVATAR_ACTION_SEND].PROC = W_AVATAR_ACTION_SEND;
	// W_UPDATE_AVATAR_ACTION
	mWorkerPacketSize[P_UPDATE_AVATAR_ACTION] = S_UPDATE_AVATAR_ACTION;
	W_FUNCTION[P_UPDATE_AVATAR_ACTION].PROC = W_UPDATE_AVATAR_ACTION;
	// AUTOPOTS
	mWorkerPacketSize[P_CHANGE_AUTO_INFO] = S_CHANGE_AUTO_INFO;
	W_FUNCTION[P_CHANGE_AUTO_INFO].PROC = W_CHANGE_AUTO_INFO;
	// W_USE_HOTKEY_ITEM_SEND
	mWorkerPacketSize[P_USE_HOTKEY_ITEM_SEND] = S_USE_HOTKEY_ITEM_SEND;
	W_FUNCTION[P_USE_HOTKEY_ITEM_SEND].PROC = W_USE_HOTKEY_ITEM_SEND;
	// W_USE_INVENTORY_ITEM_SEND
	mWorkerPacketSize[P_USE_INVENTORY_ITEM_SEND] = S_USE_INVENTORY_ITEM_SEND;
	W_FUNCTION[P_USE_INVENTORY_ITEM_SEND].PROC = W_USE_INVENTORY_ITEM_SEND;
	// W_TRIBE_BANK_SEND
	mWorkerPacketSize[P_TRIBE_BANK_SEND] = S_TRIBE_BANK_SEND;
	W_FUNCTION[P_TRIBE_BANK_SEND].PROC = W_TRIBE_BANK_SEND;
	// W_GENERAL_CHAT_SEND
	mWorkerPacketSize[P_SECRET_CHAT_SEND] = S_SECRET_CHAT_SEND;
	W_FUNCTION[P_SECRET_CHAT_SEND].PROC = W_SECRET_CHAT_SEND;
	// W_SECRET_CHAT_SEND
	mWorkerPacketSize[P_GENERAL_CHAT_SEND] = S_GENERAL_CHAT_SEND;
	W_FUNCTION[P_GENERAL_CHAT_SEND].PROC = W_GENERAL_CHAT_SEND;
	// W_TRIBE_CHAT_SEND
	mWorkerPacketSize[P_TRIBE_CHAT_SEND] = S_TRIBE_CHAT_SEND;
	W_FUNCTION[P_TRIBE_CHAT_SEND].PROC = W_TRIBE_CHAT_SEND;
	// W_FACTION_NOTICE_SEND
	mWorkerPacketSize[P_FACTION_NOTICE_SEND] = S_FACTION_NOTICE_SEND;
	W_FUNCTION[P_FACTION_NOTICE_SEND].PROC = W_FACTION_NOTICE_SEND;
	// W_PROCESS_DATA_SEND
	mWorkerPacketSize[P_PROCESS_DATA_SEND] = S_PROCESS_DATA_SEND;
	W_FUNCTION[P_PROCESS_DATA_SEND].PROC = W_PROCESS_DATA_SEND;
	// W_IMPROVE_ITEM_SEND
	mWorkerPacketSize[P_IMPROVE_ITEM_SEND] = S_IMPROVE_ITEM_SEND;
	W_FUNCTION[P_IMPROVE_ITEM_SEND].PROC = W_IMPROVE_ITEM_SEND;
	// W_ADD_ITEM_SEND
	mWorkerPacketSize[P_ADD_ITEM_SEND] = S_ADD_ITEM_SEND;
	W_FUNCTION[P_ADD_ITEM_SEND].PROC = W_ADD_ITEM_SEND;
	// W_TRADE_ASK_SEND
	mWorkerPacketSize[P_TRADE_ASK_SEND] = S_TRADE_ASK_SEND;
	W_FUNCTION[P_TRADE_ASK_SEND].PROC = W_TRADE_ASK_SEND;
	// W_TRADE_CANCEL_SEND
	mWorkerPacketSize[P_TRADE_CANCEL_SEND] = S_TRADE_CANCEL_SEND;
	W_FUNCTION[P_TRADE_CANCEL_SEND].PROC = W_TRADE_CANCEL_SEND;
	// W_TRADE_ANSWER_SEND
	mWorkerPacketSize[P_TRADE_ANSWER_SEND] = S_TRADE_ANSWER_SEND;
	W_FUNCTION[P_TRADE_ANSWER_SEND].PROC = W_TRADE_ANSWER_SEND;
	// W_TRADE_START_SEND
	mWorkerPacketSize[P_TRADE_START_SEND] = S_TRADE_START_SEND;
	W_FUNCTION[P_TRADE_START_SEND].PROC = W_TRADE_START_SEND;
	// W_TRADE_MENU_SEND
	mWorkerPacketSize[P_TRADE_MENU_SEND] = S_TRADE_MENU_SEND;
	W_FUNCTION[P_TRADE_MENU_SEND].PROC = W_TRADE_MENU_SEND;
	// W_TRADE_END_SEND
	mWorkerPacketSize[P_TRADE_END_SEND] = S_TRADE_END_SEND;
	W_FUNCTION[P_TRADE_END_SEND].PROC = W_TRADE_END_SEND;
	// W_FRIEND_ASK_SEND
	mWorkerPacketSize[P_FRIEND_ASK_SEND] = S_FRIEND_ASK_SEND;
	W_FUNCTION[P_FRIEND_ASK_SEND].PROC = W_FRIEND_ASK_SEND;
	// W_FRIEND_CANCEL_SEND
	mWorkerPacketSize[P_FRIEND_CANCEL_SEND] = S_FRIEND_CANCEL_SEND;
	W_FUNCTION[P_FRIEND_CANCEL_SEND].PROC = W_FRIEND_CANCEL_SEND;
	// W_FRIEND_ANSWER_SEND
	mWorkerPacketSize[P_FRIEND_ANSWER_SEND] = S_FRIEND_ANSWER_SEND;
	W_FUNCTION[P_FRIEND_ANSWER_SEND].PROC = W_FRIEND_ANSWER_SEND;
	// W_FRIEND_MAKE_SEND
	mWorkerPacketSize[P_FRIEND_MAKE_SEND] = S_FRIEND_MAKE_SEND;
	W_FUNCTION[P_FRIEND_MAKE_SEND].PROC = W_FRIEND_MAKE_SEND;
	// W_FRIEND_FIND_SEND
	mWorkerPacketSize[P_FRIEND_FIND_SEND] = S_FRIEND_FIND_SEND;
	W_FUNCTION[P_FRIEND_FIND_SEND].PROC = W_FRIEND_FIND_SEND;
	// W_FRIEND_DELETE_SEND
	mWorkerPacketSize[P_FRIEND_DELETE_SEND] = S_FRIEND_DELETE_SEND;
	W_FUNCTION[P_FRIEND_DELETE_SEND].PROC = W_FRIEND_DELETE_SEND;
	// W_PROCESS_ATTACK_SEND
	mWorkerPacketSize[P_PROCESS_ATTACK_SEND] = S_PROCESS_ATTACK_SEND;
	W_FUNCTION[P_PROCESS_ATTACK_SEND].PROC = W_PROCESS_ATTACK_SEND;
	// W_ANIMAL_STATE_SEND
	mWorkerPacketSize[P_ANIMAL_STATE_SEND] = S_ANIMAL_STATE_SEND;
	W_FUNCTION[P_ANIMAL_STATE_SEND].PROC = W_ANIMAL_STATE_SEND;
	// W_BUY_CASH_ITEM_SEND
	mWorkerPacketSize[P_BUY_CASH_ITEM_SEND] = S_BUY_CASH_ITEM_SEND;
	W_FUNCTION[P_BUY_CASH_ITEM_SEND].PROC = W_BUY_CASH_ITEM_SEND;
	// W_MAKE_ITEM_SEND
	mWorkerPacketSize[P_MAKE_ITEM_SEND] = S_MAKE_ITEM_SEND;
	W_FUNCTION[P_MAKE_ITEM_SEND].PROC = W_MAKE_ITEM_SEND;
	// W_ABSORB_STATE_SEND
	mWorkerPacketSize[P_ABSORB_STATE_SEND] = S_ABSORB_STATE_SEND;
	W_FUNCTION[P_ABSORB_STATE_SEND].PROC = W_ABSORB_STATE_SEND;
	// W_COSTUME_STATE
	mWorkerPacketSize[P_COSTUME_STATE_SEND] = S_COSTUME_STATE_SEND;
	W_FUNCTION[P_COSTUME_STATE_SEND].PROC = W_COSTUME_STATE_SEND;
	// W_TRIBE_WORK_SEND
	mWorkerPacketSize[P_TRIBE_WORK_SEND] = S_TRIBE_WORK_SEND;
	W_FUNCTION[P_TRIBE_WORK_SEND].PROC = W_TRIBE_WORK_SEND;
	// W_DEMAND_ZONE_SERVER_INFO_2
	mWorkerPacketSize[P_DEMAND_ZONE_SERVER_INFO_2] = S_DEMAND_ZONE_SERVER_INFO_2;
	W_FUNCTION[P_DEMAND_ZONE_SERVER_INFO_2].PROC = W_DEMAND_ZONE_SERVER_INFO_2;
	// W_FAIL_MOVE_ZONE_2_SEND
	mWorkerPacketSize[P_FAIL_MOVE_ZONE_2_SEND] = S_FAIL_MOVE_ZONE_2_SEND;
	W_FUNCTION[P_FAIL_MOVE_ZONE_2_SEND].PROC = W_FAIL_MOVE_ZONE_2_SEND;
	// W_START_PSHOP_SEND
	mWorkerPacketSize[P_START_PSHOP_SEND] = S_START_PSHOP_SEND;
	W_FUNCTION[P_START_PSHOP_SEND].PROC = W_START_PSHOP_SEND;
	// W_END_PSHOP_SEND
	mWorkerPacketSize[P_END_PSHOP_SEND] = S_END_PSHOP_SEND;
	W_FUNCTION[P_END_PSHOP_SEND].PROC = W_END_PSHOP_SEND;
	// W_DEMAND_PSHOP_SEND
	mWorkerPacketSize[P_DEMAND_PSHOP_SEND] = S_DEMAND_PSHOP_SEND;
	W_FUNCTION[P_DEMAND_PSHOP_SEND].PROC = W_DEMAND_PSHOP_SEND;
	// W_PSHOP_ITEM_INFO_SEND
	mWorkerPacketSize[P_PSHOP_ITEM_INFO_SEND] = S_PSHOP_ITEM_INFO_SEND;
	W_FUNCTION[P_PSHOP_ITEM_INFO_SEND].PROC = W_PSHOP_ITEM_INFO_SEND;
	// W_BUY_PSHOP_SEND
	mWorkerPacketSize[P_BUY_PSHOP_SEND] = S_BUY_PSHOP_SEND;
	W_FUNCTION[P_BUY_PSHOP_SEND].PROC = W_BUY_PSHOP_SEND;
	// W_GET_CASH_SIZE_SEND
	mWorkerPacketSize[P_GET_CASH_SIZE_SEND] = S_GET_CASH_SIZE_SEND;
	W_FUNCTION[P_GET_CASH_SIZE_SEND].PROC = W_GET_CASH_SIZE_SEND;
	// W_DUEL_ASK_SEND
	mWorkerPacketSize[P_DUEL_ASK_SEND] = S_DUEL_ASK_SEND;
	W_FUNCTION[P_DUEL_ASK_SEND].PROC = W_DUEL_ASK_SEND;
	// W_DUEL_CANCEL_SEND
	mWorkerPacketSize[P_DUEL_CANCEL_SEND] = S_DUEL_CANCEL_SEND;
	W_FUNCTION[P_DUEL_CANCEL_SEND].PROC = W_DUEL_CANCEL_SEND;
	// W_DUEL_ANSWER_SEND
	mWorkerPacketSize[P_DUEL_ANSWER_SEND] = S_DUEL_ANSWER_SEND;
	W_FUNCTION[P_DUEL_ANSWER_SEND].PROC = W_DUEL_ANSWER_SEND;
	// W_DUEL_START_SEND
	mWorkerPacketSize[P_DUEL_START_SEND] = S_DUEL_START_SEND;
	W_FUNCTION[P_DUEL_START_SEND].PROC = W_DUEL_START_SEND;
	// W_TRIBE_VOTE_SEND
	mWorkerPacketSize[P_TRIBE_VOTE_SEND] = S_TRIBE_VOTE_SEND;
	W_FUNCTION[P_TRIBE_VOTE_SEND].PROC = W_TRIBE_VOTE_SEND;

	// W_GET_CASH_ITEM_INFO_SEND
	mWorkerPacketSize[P_GET_CASH_ITEM_INFO_SEND] = S_GET_CASH_ITEM_INFO_SEND;
	W_FUNCTION[P_GET_CASH_ITEM_INFO_SEND].PROC = W_GET_CASH_ITEM_INFO_SEND;

	// AutoHunt ??
	mWorkerPacketSize[P_AUTO_CONFIG_SEND] = S_AUTO_CONFIG_SEND;
	W_FUNCTION[P_AUTO_CONFIG_SEND].PROC = W_AUTO_CONFIG_SEND;

	mWorkerPacketSize[P_AUTOBUFF_REGISTER_SEND] = S_AUTOBUFF_REGISTER_SEND;
	W_FUNCTION[P_AUTOBUFF_REGISTER_SEND].PROC = W_AUTOBUFF_REGISTER_SEND;

	mWorkerPacketSize[P_AUTOBUFF_SEND] = S_AUTOBUFF_SEND;
	W_FUNCTION[P_AUTOBUFF_SEND].PROC = W_AUTOBUFF_SEND;

	// W_PET_COMBINE_SEND
	mWorkerPacketSize[P_PET_COMBINE_SEND] = S_PET_COMBINE_SEND;
	W_FUNCTION[P_PET_COMBINE_SEND].PROC = W_PET_COMBINE_SEND;

	// W_MAKE_SKILL_SEND
	mWorkerPacketSize[P_MAKE_SKILL_SEND] = S_MAKE_SKILL_SEND;
	W_FUNCTION[P_MAKE_SKILL_SEND].PROC = W_MAKE_SKILL_SEND;

	// W_GEAR_BREAK_SEND
	mWorkerPacketSize[P_GEAR_BREAK_SEND] = S_GEAR_BREAK_SEND;
	W_FUNCTION[P_GEAR_BREAK_SEND].PROC = W_GEAR_BREAK_SEND;

	// W_TRIBE_NOTICE_SEND
	mWorkerPacketSize[P_TRIBE_NOTICE_SEND] = S_TRIBE_NOTICE_SEND;
	W_FUNCTION[P_TRIBE_NOTICE_SEND].PROC = W_TRIBE_NOTICE_SEND;

	// W_GENERAL_NOTICE_SEND
	mWorkerPacketSize[P_GENERAL_NOTICE_SEND] = S_GENERAL_NOTICE_SEND;
	W_FUNCTION[P_GENERAL_NOTICE_SEND].PROC = W_GENERAL_NOTICE_SEND;

	// W_CHAR_RANK_BUFF_SEND
	mWorkerPacketSize[P_CHAR_RANK_BUFF_SEND] = S_CHAR_RANK_BUFF_SEND;
	W_FUNCTION[P_CHAR_RANK_BUFF_SEND].PROC = W_CHAR_RANK_BUFF_SEND;

	// W_GUILD_ASK_SEND
	mWorkerPacketSize[P_GUILD_ASK_SEND] = S_GUILD_ASK_SEND;
	W_FUNCTION[P_GUILD_ASK_SEND].PROC = W_GUILD_ASK_SEND;
	// W_GUILD_CANCEL_SEND
	mWorkerPacketSize[P_GUILD_CANCEL_SEND] = S_GUILD_CANCEL_SEND;
	W_FUNCTION[P_GUILD_CANCEL_SEND].PROC = W_GUILD_CANCEL_SEND;
	// W_GUILD_ANSWER_SEND
	mWorkerPacketSize[P_GUILD_ANSWER_SEND] = S_GUILD_ANSWER_SEND;
	W_FUNCTION[P_GUILD_ANSWER_SEND].PROC = W_GUILD_ANSWER_SEND;
	// W_GUILD_WORK_SEND
	mWorkerPacketSize[P_GUILD_WORK_SEND] = S_GUILD_WORK_SEND;
	W_FUNCTION[P_GUILD_WORK_SEND].PROC = W_GUILD_WORK_SEND;
	// W_GUILD_NOTICE_SEND
	mWorkerPacketSize[P_GUILD_NOTICE_SEND] = S_GUILD_NOTICE_SEND;
	W_FUNCTION[P_GUILD_NOTICE_SEND].PROC = W_GUILD_NOTICE_SEND;
	// W_GUILD_CHAT_SEND
	mWorkerPacketSize[P_GUILD_CHAT_SEND] = S_GUILD_CHAT_SEND;
	W_FUNCTION[P_GUILD_CHAT_SEND].PROC = W_GUILD_CHAT_SEND;
	// W_GUILD_FIND_SEND
	mWorkerPacketSize[P_GUILD_FIND_SEND] = S_GUILD_FIND_SEND;
	W_FUNCTION[P_GUILD_FIND_SEND].PROC = W_GUILD_FIND_SEND;
	// W_PARTY_ASK_SEND
	mWorkerPacketSize[P_PARTY_ASK_SEND] = S_PARTY_ASK_SEND;
	W_FUNCTION[P_PARTY_ASK_SEND].PROC = W_PARTY_ASK_SEND;
	// W_PARTY_CANCEL_SEND
	mWorkerPacketSize[P_PARTY_CANCEL_SEND] = S_PARTY_CANCEL_SEND;
	W_FUNCTION[P_PARTY_CANCEL_SEND].PROC = W_PARTY_CANCEL_SEND;
	// W_PARTY_ANSWER_SEND
	mWorkerPacketSize[P_PARTY_ANSWER_SEND] = S_PARTY_ANSWER_SEND;
	W_FUNCTION[P_PARTY_ANSWER_SEND].PROC = W_PARTY_ANSWER_SEND;
	// W_PARTY_MAKE_SEND
	mWorkerPacketSize[160] = 9;
	W_FUNCTION[160].PROC = W_PARTY_MAKE_SEND;
	// W_PARTY_JOIN_SEND
	mWorkerPacketSize[161] = 9;
	W_FUNCTION[161].PROC = W_PARTY_JOIN_SEND;
	// W_PARTY_CHAT_SEND
	mWorkerPacketSize[P_PARTY_CHAT_SEND] = S_PARTY_CHAT_SEND;
	W_FUNCTION[P_PARTY_CHAT_SEND].PROC = W_PARTY_CHAT_SEND;
	// W_PARTY_LEAVE_SEND
	mWorkerPacketSize[P_PARTY_LEAVE_SEND] = S_PARTY_LEAVE_SEND;
	W_FUNCTION[P_PARTY_LEAVE_SEND].PROC = W_PARTY_LEAVE_SEND;
	// W_PARTY_EXILE_SEND
	mWorkerPacketSize[P_PARTY_EXILE_SEND] = S_PARTY_EXILE_SEND;
	W_FUNCTION[P_PARTY_EXILE_SEND].PROC = W_PARTY_EXILE_SEND;
	// W_PARTY_PROMOTE_SEND
	mWorkerPacketSize[P_PARTY_BREAK_SEND] = S_PARTY_BREAK_SEND;
	W_FUNCTION[P_PARTY_BREAK_SEND].PROC = W_PARTY_BREAK_SEND;
	// W_REFINE_SEND
	mWorkerPacketSize[P_REFINE_SEND] = S_REFINE_SEND;
	W_FUNCTION[P_REFINE_SEND].PROC = W_REFINE_SEND;
	// W_HIGH_ITEM_SEND
	mWorkerPacketSize[P_HIGH_ITEM_SEND] = S_HIGH_ITEM_SEND;
	W_FUNCTION[P_HIGH_ITEM_SEND].PROC = W_HIGH_ITEM_SEND;
	// W_LOW_ITEM_SEND
	mWorkerPacketSize[P_LOW_ITEM_SEND] = S_LOW_ITEM_SEND;
	W_FUNCTION[P_LOW_ITEM_SEND].PROC = W_LOW_ITEM_SEND;
	// W_TIME_EFFECT_SEND
	mWorkerPacketSize[P_TIME_EFFECT_SEND] = S_TIME_EFFECT_SEND;
	W_FUNCTION[P_TIME_EFFECT_SEND].PROC = W_TIME_EFFECT_SEND;
	// W_DAILY_MISSION_SEND
	mWorkerPacketSize[P_DAILY_MISSION_SEND] = S_DAILY_MISSION_SEND;
	W_FUNCTION[P_DAILY_MISSION_SEND].PROC = W_DAILY_MISSION_SEND;
	// W_EXCHANGE_ITEM_SEND
	mWorkerPacketSize[P_EXCHANGE_ITEM_SEND] = S_EXCHANGE_ITEM_SEND;
	W_FUNCTION[P_EXCHANGE_ITEM_SEND].PROC = W_EXCHANGE_ITEM_SEND;
	// W_WARLORD_V2_SEND
	mWorkerPacketSize[P_WARLORD_V2_SEND] = S_WARLORD_V2_SEND;
	W_FUNCTION[P_WARLORD_V2_SEND].PROC = W_WARLORD_V2_SEND;
	// GENERAL_SHOUT_SEND
	mWorkerPacketSize[P_GENERAL_SHOUT_SEND] = S_GENERAL_SHOUT_SEND;
	W_FUNCTION[P_GENERAL_SHOUT_SEND].PROC = W_GENERAL_SHOUT_SEND;
	// SOCKET_ITEM_SEND
	mWorkerPacketSize[P_SOCKET_ITEM_SEND] = S_SOCKET_ITEM_SEND;
	W_FUNCTION[P_SOCKET_ITEM_SEND].PROC = W_SOCKET_ITEM_SEND;
	// TEACHER_ASK_SEND
	mWorkerPacketSize[P_TEACHER_ASK_SEND] = S_TEACHER_ASK_SEND;
	W_FUNCTION[P_TEACHER_ASK_SEND].PROC = W_TEACHER_ASK_SEND;
	// TEACHER_ANSWER_SEND
	mWorkerPacketSize[P_TEACHER_ANSWER_SEND] = S_TEACHER_ANSWER_SEND;
	W_FUNCTION[P_TEACHER_ANSWER_SEND].PROC = W_TEACHER_ANSWER_SEND;
	// TEACHER_CANCEL_SEND
	mWorkerPacketSize[P_TEACHER_CANCEL_SEND] = S_TEACHER_CANCEL_SEND;
	W_FUNCTION[P_TEACHER_CANCEL_SEND].PROC = W_TEACHER_CANCEL_SEND;
	// TEACHER_START_SEND
	mWorkerPacketSize[P_TEACHER_START_SEND] = S_TEACHER_START_SEND;
	W_FUNCTION[P_TEACHER_START_SEND].PROC = W_TEACHER_START_SEND;
	// TEACHER_STATE_SEND
	mWorkerPacketSize[P_TEACHER_STATE_SEND] = S_TEACHER_STATE_SEND;
	W_FUNCTION[P_TEACHER_STATE_SEND].PROC = W_TEACHER_STATE_SEND;
	// TEACHER_END_SEND
	mWorkerPacketSize[P_TEACHER_END_SEND] = S_TEACHER_END_SEND;
	W_FUNCTION[P_TEACHER_END_SEND].PROC = W_TEACHER_END_SEND;
	// CHANGE_TO_TRIBE4
	mWorkerPacketSize[P_CHANGE_TO_TRIBE4_SEND] = S_CHANGE_TO_TRIBE4_SEND;
	W_FUNCTION[P_CHANGE_TO_TRIBE4_SEND].PROC = W_CHANGE_TO_TRIBE4_SEND;
	// W_BOOZE_DRINK_SEND
	mWorkerPacketSize[P_BOOZE_DRINK_SEND] = S_BOOZE_DRINK_SEND;
	W_FUNCTION[P_BOOZE_DRINK_SEND].PROC = W_BOOZE_DRINK_SEND;
	// W_COMBINE_G12_PET_SEND
	mWorkerPacketSize[P_COMBINE_G12_PET_SEND] = S_COMBINE_G12_PET_SEND;
	W_FUNCTION[P_COMBINE_G12_PET_SEND].PROC = W_COMBINE_G12_PET_SEND;
	// ADD_AMULET_ABILITY
	mWorkerPacketSize[P_ADD_AMULET_ABILITY_SEND] = S_ADD_AMULET_ABILITY_SEND;
	W_FUNCTION[P_ADD_AMULET_ABILITY_SEND].PROC = W_ADD_AMULET_ABILITY_SEND;
	// HERO_RANKING_SEND
	mWorkerPacketSize[P_HERO_RANKING_SEND] = S_HERO_RANKING_SEND;
	W_FUNCTION[P_HERO_RANKING_SEND].PROC = W_HERO_RANKING_SEND;
	// W_CLAIM_HERO_RANK_SEND
	mWorkerPacketSize[P_CLAIM_HERO_RANK_REWARD_SEND] = S_CLAIM_HERO_RANK_REWARD_SEND;
	W_FUNCTION[P_CLAIM_HERO_RANK_REWARD_SEND].PROC = W_CLAIM_HERO_RANK_REWARD_SEND;
	// W_ULTIMATE_ENCHANT_SEND
	mWorkerPacketSize[P_ULTIMATE_ENCHANT_SEND] = S_ULTIMATE_ENCHANT_SEND;
	W_FUNCTION[P_ULTIMATE_ENCHANT_SEND].PROC = W_ULTIMATE_ENCHANT_SEND;
	// W_COSTUME_HIDE_SEND
	mWorkerPacketSize[P_COSTUME_HIDE_SEND] = S_COSTUME_HIDE_SEND;
	W_FUNCTION[P_COSTUME_HIDE_SEND].PROC = W_COSTUME_HIDE_SEND;
	// W_ENGRAVE_WEAPONS_SEND
	mWorkerPacketSize[P_ENGRAVE_ITEM_SEND] = S_ENGRAVE_ITEM_SEND;
	W_FUNCTION[P_ENGRAVE_ITEM_SEND].PROC = W_ENGRAVE_ITEM_SEND;
	// W_WARLORDV2_TO_LEGENDARY_SEND
	mWorkerPacketSize[P_WARLORDV2_TO_LEGENDARY_SEND] = S_WARLORDV2_TO_LEGENDARY_SEND;
	W_FUNCTION[P_WARLORDV2_TO_LEGENDARY_SEND].PROC = W_WARLORDV2_TO_LEGENDARY_SEND;
	// W_TOWER_UPGRADE_SEND
	mWorkerPacketSize[P_TOWER_UPGRADE_SEND] = S_TOWER_UPGRADE_SEND;
	W_FUNCTION[P_TOWER_UPGRADE_SEND].PROC = W_TOWER_UPGRADE_SEND;
	// W_RAGE_BURST
	mWorkerPacketSize[P_RAGE_BURST_SEND] = S_RAGE_BURST_SEND;
	W_FUNCTION[P_RAGE_BURST_SEND].PROC = W_RAGE_BURST_SEND;
	// W_DEMAND_BLOODSTAINED_SHOP_INFO_SEND
	mWorkerPacketSize[P_DEMAND_BLOODSTAINED_SHOP_INFO_SEND] = S_DEMAND_BLOODSTAINED_SHOP_INFO_SEND;
	W_FUNCTION[P_DEMAND_BLOODSTAINED_SHOP_INFO_SEND].PROC = W_DEMAND_BLOODSTAINED_SHOP_INFO_SEND;
	// W_BUY_BLOODSTAINED_SHOP_SEND
	mWorkerPacketSize[P_BUY_BLOODSTAINED_SHOP_SEND] = S_BUY_BLOODSTAINED_SHOP_SEND;
	W_FUNCTION[P_BUY_BLOODSTAINED_SHOP_SEND].PROC = W_BUY_BLOODSTAINED_SHOP_SEND;
#ifdef CAPSULE
	// W_BUY_CAPSULE_SEND
	mWorkerPacketSize[P_BUY_CAPSULE_SEND] = S_BUY_CAPSULE_SEND;
	W_FUNCTION[P_BUY_CAPSULE_SEND].PROC = W_BUY_CAPSULE_SEND;
#endif
	// W_PROXY_MENU
	mWorkerPacketSize[P_PROXY_MENU_SEND] = S_PROXY_MENU_SEND;
	W_FUNCTION[P_PROXY_MENU_SEND].PROC = W_PROXY_MENU_SEND;
	// W_BUY_PROXY_SHOP
	mWorkerPacketSize[P_BUY_PROXY_SHOP] = S_BUY_PROXY_SHOP;
	W_FUNCTION[P_BUY_PROXY_SHOP].PROC = W_BUY_PROXY_SHOP;
	// W_CLAIM_MONEY_PROXY_SHOP_SEND
	mWorkerPacketSize[P_CLAIM_MONEY_PROXY_SHOP_SEND] = S_CLAIM_MONEY_PROXY_SHOP_SEND;
	W_FUNCTION[P_CLAIM_MONEY_PROXY_SHOP_SEND].PROC = W_CLAIM_MONEY_PROXY_SHOP_SEND;
#ifdef FISHING
	// W_FISHING_START_SEND
	mWorkerPacketSize[P_FISHING_STATE_SEND] = S_FISHING_STATE_SEND;
	W_FUNCTION[P_FISHING_STATE_SEND].PROC = W_FISHING_STATE_SEND;
	// W_FISHING_STATE_SEND
	mWorkerPacketSize[P_FISHING_RESULT_SEND] = S_FISHING_RESULT_SEND;
	W_FUNCTION[P_FISHING_RESULT_SEND].PROC = W_FISHING_RESULT_SEND;
	// W_FISHING_NEW_SEND
	mWorkerPacketSize[P_FISHING_REWARD_SEND] = S_FISHING_REWARD_SEND;
	W_FUNCTION[P_FISHING_REWARD_SEND].PROC = W_FISHING_REWARD_SEND;
#endif
#ifdef __DICEGAME__
	// W_DICE_GAME_SEND
	mWorkerPacketSize[P_DICE_GAME_SEND] = S_DICE_GAME_SEND;
	W_FUNCTION[P_DICE_GAME_SEND].PROC = W_DICE_GAME_SEND;
#endif
	// W_FACTION_TRAP_ACTIVATE
	mWorkerPacketSize[P_FACTION_TRAP_ACTIVATE] = S_FACTION_TRAP_ACTIVATE;
	W_FUNCTION[P_FACTION_TRAP_ACTIVATE].PROC = W_FACTION_TRAP_ACTIVATE;
	// W_CLOAK_UPGRADE_SEND
	mWorkerPacketSize[P_CLOAK_UPGRADE_SEND] = S_CLOAK_UPGRADE_SEND;
	W_FUNCTION[P_CLOAK_UPGRADE_SEND].PROC = W_CLOAK_UPGRADE_SEND;
	// W_UNSEAL_LEGENDARY_SEND
	mWorkerPacketSize[P_UNSEAL_LEGENDARY_SEND] = S_UNSEAL_LEGENDARY_SEND;
	W_FUNCTION[P_UNSEAL_LEGENDARY_SEND].PROC = W_UNSEAL_LEGENDARY_SEND;
	// W_UNSEAL_LEGENDARY_SEND
	mWorkerPacketSize[P_CRAFT_COSTUME_SEND] = S_CRAFT_COSTUME_SEND;
	W_FUNCTION[P_CRAFT_COSTUME_SEND].PROC = W_CRAFT_COSTUME_SEND;


	return TRUE;
}


//FREE
void MyWork::Free(void)
{
}